### ISSUE TITLE
Docs still link to BitBucket

### ISSUE THREAD

**Issue by lukebennett88** [brighte-labs/spark-web#13]
We need to update the docs to link to new URLs on GitHub

**Comment by justinfaynhan** [comment]
See https://github.com/brighte-labs/spark-web/pull/58 for relevant fix

**Comment by tamm** [comment]
@lukebennett88 @justinfaynhan Looks like #58 closed this?

**Comment by lukebennett88** [comment]
Thanks Tamm. You're right.
