### ISSUE TITLE
RadioGroup: a11y concerns

### ISSUE THREAD

**Issue by jossmac** [brighte-labs/spark-web#15]
The [RadioGroup](https://spark.brighte.com.au/package/radio#radiogroup) component employs `display: contents`, which unfortunately can [negatively affect the accessibility](https://bugs.webkit.org/show_bug.cgi?id=185679) of the element it's applied to in some browsers.

A radio group without a "caption" presents some issues too, consider [fieldset](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset) + [legend](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend).

**Comment by szhang-brighte** [comment]
Looks like this bug is fixed: https://bugs.webkit.org/show_bug.cgi?id=185679

**Comment by szhang-brighte** [comment]
Looks like the bug is fixed: [here](https://bugs.webkit.org/show_bug.cgi?id=185679#c15)
